version: 2
updates:
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - tadayosi
      - phantomjinx
      - mmelko
      - jsolovjo
      - mmuzikar
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: monthly
    target-branch: '4.0.x'
    reviewers:
      - tadayosi
      - phantomjinx
      - mmelko
      - jsolovjo
      - mmuzikar
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: monthly
    target-branch: '3.x'
    reviewers:
      - tadayosi
      - phantomjinx
      - mmelko
      - jsolovjo
      - mmuzikar
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - tadayosi
      - phantomjinx
      - mmelko
      - jsolovjo
      - mmuzikar
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - tadayosi
      - phantomjinx
      - mmelko
      - jsolovjo
      - mmuzikar
